version: "3.9"
services:
  code:
    build: .
    ports:
      - "22:22"
  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: simple_ci
      POSTGRES_USER: simple_ci
